name: Deploy Static Site (Case-Sensitive Support)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add Jekyll config to recognize Index.html (capital I)
      - name: Create case-sensitive config
        run: |
          echo "include: [Index.html]" > _config.yml
          echo "Created _config.yml for case sensitivity"

      # Verify files (debugging)
      - name: List files
        run: ls -la

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "." # Includes all files (both Index.html and _config.yml)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
