name: Deploy Static Site

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Handle case sensitivity for Index.html
      - name: Configure Jekyll (if needed)
        run: |
          if [ -f "Index.html" ]; then
            echo "include: [Index.html]" > _config.yml
            echo "Case sensitivity configured"
          fi

      # 3. Set up GitHub Pages
      - uses: actions/configure-pages@v3

      # 4. Upload files to Pages
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "."

      # 5. Deploy
      - uses: actions/deploy-pages@v2
        id: deployment
